#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean ./src/thermophysicalModels/basic
wclean ./src/thermophysicalModels/SLGThermo
wclean ./src/thermophysicalModels/thermophysicalProperties
wclean ./src/dynamicFvMesh
wclean ./src/functionObjects/field
wclean ./src/regionModels/surfaceFilmModels
wclean ./src/dfChemistryModel
wclean ./src/lagrangian/spray
wclean ./src/lagrangian/turbulence
wclean ./src/lagrangian/intermediate
wclean ./src/dynamicMesh
wclean ./src/dfCombustionModels
wclean ./src/TurbulenceModels/compressible
wclean ./src/TurbulenceModels/turbulenceModels
wclean ./src/dfCanteraMixture
wclean ./applications/utilities/flameSpeed
wclean ./applications/solvers/dfSprayFoam
wclean ./applications/solvers/df0DFoam
wclean ./applications/solvers/dfLowMachFoam
wclean ./applications/solvers/dfHighSpeedFoam

rm -rf src_orig/
rm -rf bin/
rm -rf lib/
