#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake src/thermophysicalModels/thermophysicalProperties
wmake src/thermophysicalModels/basic
wmake src/functionObjects/field
wmake src/dfCanteraMixture
wmake src/thermophysicalModels/SLGThermo
wmake src/dfChemistryModel
wmake src/TurbulenceModels/compressible
wmake src/TurbulenceModels/turbulenceModels
wmake src/regionModels/surfaceFilmModels
src/lagrangian/Allwmake $targetType $*
wmake src/dfCombustionModels
wmake src/dynamicMesh
wmake src/dynamicFvMesh

wmake applications/solvers/df0DFoam
wmake applications/solvers/dfLowMachFoam
wmake applications/solvers/dfHighSpeedFoam
wmake applications/solvers/dfSprayFoam

wmake applications/utilities/flameSpeed
